{
 "title": "Example Metrics",
 "description": "Dashboard with example metrics for presentation",
 "tags": [
  "python",
  "example",
  "metrics",
  "test"
 ],
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "DataSource", "label": "DataSource", "query": "prometheus" }
  ]
 },
 "panels": [
  { "title": "Danger Value", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Prod Danger Alert",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "max(example_danger) by (job, env)",
     "legendFormat": "{{env}}"
    }
   ]
  },
  {
   "title": "GAUGE Danger Alarm",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "max by (env) (example_danger)", "legendFormat": "{{env}}" }
   ]
  },
  {
   "title": "Counter",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 },
   "collapsed": true,
   "panels": [
    {
     "title": "COUNTER Total Requests by handler and method",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 10 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum by (handler, method) (example_requests_total)",
       "legendFormat": "{{method}} {{handler}} "
      }
     ]
    },
    {
     "title": "COUNTER Request changes",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 10 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum by (handler, method) (rate(example_requests_total[1m]))",
       "legendFormat": "{{method}} {{handler}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Gauge",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 },
   "collapsed": true,
   "panels": [
    {
     "title": "GAUGE Bitcoin/USD",
     "type": "gauge",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 11 },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "max(example_bitcoin_exchange_rate_dollar)"
      }
     ]
    },
    {
     "title": "GAUGE Bitcoin/USD",
     "type": "stat",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 11 },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "max(example_bitcoin_exchange_rate_dollar)"
      }
     ]
    },
    {
     "title": "Bitcoin Predict",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 19 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "max(predict_linear(example_bitcoin_exchange_rate_dollar[5m], 60*5))",
       "legendFormat": "predict"
      },
      {
       "expr": "max(example_bitcoin_exchange_rate_dollar)",
       "legendFormat": "max"
      }
     ]
    },
    {
     "title": "Bitcoin Change",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 19 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "max(deriv(example_bitcoin_exchange_rate_dollar[5m]))",
       "legendFormat": "change"
      }
     ]
    }
   ]
  },
  {
   "title": "Histogram",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 },
   "collapsed": true,
   "panels": [
    {
     "title": "HISTOGRAM Latency Quantile",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 12 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.95, sum by (handler, le) (rate(example_requests_latency_histogram_seconds_bucket[10m])))",
       "legendFormat": "0.95 {{handler}} "
      }
     ]
    },
    {
     "title": "Histogram",
     "type": "bargauge",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 12 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(increase(example_requests_latency_histogram_seconds_bucket[5m])) by (le) ",
       "legendFormat": "{{le}}"
      }
     ]
    },
    {
     "title": "Histogram Request Latency Larger than 1.0 second",
     "type": "stat",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 20 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(example_requests_latency_histogram_seconds_count - ignoring(le) example_requests_latency_histogram_seconds_bucket{le=\"1.0\"}) by (handler)",
       "legendFormat": "{{handler}}"
      }
     ]
    },
    {
     "title": "Histogram Request Latency Faster than 1.0 second in Percent",
     "type": "stat",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 20 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(example_requests_latency_histogram_seconds_bucket{le=\"1.0\"}) by (handler) / ignoring (le) sum(example_requests_latency_histogram_seconds_count) by (handler) ",
       "legendFormat": "{{handler}}"
      }
     ]
    }
   ]
  }
 ]
}