kind: PrometheusRule
apiVersion: monitoring.coreos.com/v1
metadata:
  labels:
    app: example-metrics-app
    prometheus: alert-rules
    role: alert-rules
  name: example-metrics-app-prometheus-rule
  namespace: {{ .Values.prometheus_rules.namespace }}
spec:
  groups:
    - name: env
      rules:
        - alert: ProdDangerLevelAchieved
          annotations:
            message: >-
               {{`{{`}}$labels.env{{`}}`}} danger level is more than 80 points. Found by {{`{{`}}$labels.job{{`}}`}}
          expr: >-
            max(example_danger) by (job, env) > 80
          for: 1m
          labels:
            severity: critical
