apiVersion: apps/v1
kind: Deployment
metadata:
  name: example-metrics-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: example-metrics-app
  template:
    metadata:
      labels:
        app: example-metrics-app
    spec:
      containers:
        - name: example-metrics-app
          image: {{ .Values.example.registry }}/{{ .Values.example.image }}
          imagePullPolicy: Always
          env:
            - name: FLASK_RUN_PORT
              value: {{ .Values.example.flask_port | quote }}
            - name: BASE_URL
              value: {{ .Values.example.base_url  | quote }}
          ports:
            - name: metrics
              containerPort: {{ .Values.example.metrics_port }}
            - name: http
              containerPort: {{ .Values.example.flask_port }}
---
kind: Service
apiVersion: v1
metadata:
  name: example-metrics-app
  labels:
    app: example-metrics-app
spec:
  selector:
    app: example-metrics-app
  ports:
  - name: metrics
    port: {{ .Values.example.metrics_port }}
  - name: http
    port: {{ .Values.example.flask_port }}
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: example-metrics-app
  labels:
    app: example-metrics-app
spec:
  selector:
    matchLabels:
      app: example-metrics-app
  endpoints:
  - port: metrics
    path: /

