{{- if .Values.grafana_dashboard.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: example-metrics-app-dashboards
  namespace: {{ .Values.grafana_dashboard.namespace }}
  labels:
    {{ .Values.grafana_dashboard.autodiscover_label }}: "1"
{{- if .Values.grafana_dashboard.target_directory }}
  annotations:
    k8s-sidecar-target-directory: {{ .Values.grafana_dashboard.target_directory }}
{{- end }}
data:
  example-metrics.json:
    {{ .Files.Get "dashboards/example-metrics.json" | toPrettyJson }}
{{- end }}