apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
    nginx.ingress.kubernetes.io/backend-protocol: "HTTP"
    nginx.ingress.kubernetes.io/rewrite-target: /$2
  name: example-metrics-app-nginx
spec:
  rules:
  - host: {{ .Values.example.uri }}
    http:
      paths:
      - path: {{ .Values.example.base_url }}(/|$)(.*)
        backend:
          serviceName: example-metrics-app
          servicePort: http
