apiVersion: apps/v1
kind: Deployment
metadata:
  name: example-metrics-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: example-metrics-app
  template:
    metadata:
      labels:
        app: example-metrics-app
    spec:
      containers:
        - name: example-metrics-app
          image: {{ .Values.example.registry }}/{{ .Values.example.image }}
          imagePullPolicy: Always
          env:
            - name: FLASK_RUN_PORT
              value: {{ .Values.example.flask_port | quote }}
            - name: BASE_URL
              value: {{ .Values.example.base_url  | quote }}
          ports:
            - name: metrics
              containerPort: {{ .Values.example.metrics_port }}
            - name: http
              containerPort: {{ .Values.example.flask_port }}
