apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Release.Name }}-nginx
  labels:
    app: example-metrics-app
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
    nginx.ingress.kubernetes.io/backend-protocol: "HTTP"
    nginx.ingress.kubernetes.io/rewrite-target: /$2
spec:
  rules:
  - host: {{ .Values.example.uri }}
    http:
      paths:
      - path: {{ .Values.example.base_url }}(/|$)(.*)
        pathType: Prefix
        backend:
          service:
            name: example-metrics-app
            port:
              name: http
