apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: example-metrics-app
  labels:
    app: example-metrics-app
spec:
  selector:
    matchLabels:
      app: example-metrics-app
  endpoints:
  - port: metrics
    path: /

