example:
  registry: zifter
  image: example-metrics-app:latest
  flask_port: 6000
  metrics_port: 8080
  uri: "localhost"
  base_url: "/example-metrics"

grafana_dashboard:
  enabled: "true"
  autodiscover_label: "custom-dashboard"
  namespace: "monitoring"
  target_directory: "" # /var/lib/grafana/dashboards/example

prometheus_rules:
  namespace: "monitoring"