kind: PrometheusRule
apiVersion: monitoring.coreos.com/v1
metadata:
  name: {{ .Release.Name }}-prometheus-rule
  labels:
    app: example-metrics-app
    prometheus: alert-rules
    role: alert-rules
spec:
  groups:
    - name: danger-level-env
      rules:
        - alert: EnvDangerLevelAchieved
          annotations:
            description: >-
               {{`{{`}}$labels.env{{`}}`}} danger level is more than 80 points. Found by {{`{{`}}$labels.job{{`}}`}}
          expr: >-
            max(example_danger) by (job, env) > 80
          for: 1m
          labels:
            severity: critical
            custom_label: my_custom
